type KeyType = Record<
  string,
  { value: string; latex?: string; isFunction?: boolean }
>;

export const keys: KeyType = {
  "7": { value: "7" },
  "8": { value: "8" },
  "9": { value: "9" },
  "÷": { value: "/", latex: "\\div" },
  "4": { value: "4" },
  "5": { value: "5" },
  "6": { value: "6" },
  "×": { value: "*", latex: "\\times" },
  "1": { value: "1" },
  "2": { value: "2" },
  "3": { value: "3" },
  "-": { value: "-", latex: "-" },
  "0": { value: "0" },
  "•": { value: ".", latex: "." },
  "(": { value: "(", latex: "(" },
  ")": { value: ")", latex: "}" },
  "√": { value: "sqrt(", latex: "\\sqrt{(", isFunction: true },
  "⋀": { value: "^", latex: "^" },
  π: { value: "pi", latex: "\\pi" },
  "+": { value: "+", latex: "+" },
  sin: { value: "sin(", latex: "\\sin{(", isFunction: true },
  cos: { value: "cos(", latex: "\\cos{(", isFunction: true },
  tan: { value: "tan(", latex: "\\tan{(", isFunction: true },
  log: { value: "log10(", latex: "\\log{(", isFunction: true },
  ln: { value: "log(", latex: "\\ln{(", isFunction: true },
  AC: { value: "AC" },
  "=": { value: "=" },
  EXP: { value: "E", latex: "\\times 10^" },
  M: { value: "E6", latex: "\\times 10^6" },
  G: { value: "E9", latex: "\\times 10^9" },
  T: { value: "E12", latex: "\\times 10^{12}" },
  k: { value: "E3", latex: "\\times 10^3" },
  m: { value: "E-3", latex: "\\times 10^{-3}" },
  µ: { value: "E-6", latex: "\\times 10^{-6}" },
  f: { value: "E-15", latex: "\\times 10^{-15}" },
  p: { value: "E-12", latex: "\\times 10^{-12}" },
  n: { value: "E-9", latex: "\\times 10^{-9}" },
  i: { value: "i", latex: "i" },
  ENG: { value: "" },
};
